/Xe/gun/type Volume
/Xe/gun/shape Box


/Xe/gun/halfz 1000 mm
/Xe/gun/halfx 1000 mm
/Xe/gun/halfy 1000 mm

/Xe/gun/confine RockSpawnPhysicalVolume



/Xe/gun/particle neutron
#/Xe/gun/energy 5 MeV
/Xe/gun/energytype Spectrum
/Xe/gun/energyspectrum ./notebooks/ConstantDistribution.txt
#/Xe/gun/point 0 0 3000 mm
#/Xe/gun/direction 0 0 -1000 mm
/Xe/gun/angtype iso

# Remove generated secondaries from the event
/xe/KillGeneratedParticles opticalphoton e-
