/tracking/verbose 1

#/Xe/gun/type Volume
#/Xe/gun/shape Box

# full volume
/Xe/gun/position 0 -50000 15000 mm
#/Xe/gun/halfz 25000 mm
#/Xe/gun/halfx 20000 mm
#/Xe/gun/halfy 60000 mm

#/Xe/gun/confine ConcretePhysicalVolume



/Xe/gun/particle geantino
#/Xe/gun/energy 5 MeV
/Xe/gun/energytype Spectrum
/Xe/gun/energyspectrum ./notebooks/ConstantDistribution.txt
#/Xe/gun/point 0 0 3000 mm
/Xe/gun/direction 0 1000 0 mm

# Remove generated secondaries from the event
/xe/KillGeneratedParticles opticalphoton e-
