/Xe/gun/type Volume
/Xe/gun/shape Box

# full volume
/Xe/gun/position 0 0 10000 mm
/Xe/gun/halfz 20000 mm
/Xe/gun/halfx 15000 mm
/Xe/gun/halfy 35000 mm

/Xe/gun/confine ConcretePhysicalVolume



/Xe/gun/particle neutron
#/Xe/gun/energy 5 MeV
/Xe/gun/energytype Spectrum
/Xe/gun/energyspectrum ./notebooks/ConstantDistribution.txt
/Xe/gun/point 0 0 3000 mm

# Remove generated secondaries from the event
/xe/KillGeneratedParticles opticalphoton e-